name: CI

#on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: Azure/k8s-set-context@v1
      with:
        method:  service-account
        k8s-url:  https://20.185.235.36:16443
        k8s-secret: ${{ secrets.TALAM_K8S_SECRET }}
        id:  setcontext

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/postgres-config.yml
          manifests/postgres-service.yml
          manifests/postgres-stateful.yml
        images: |
          docker.talam.io/postgres:${{ github.sha }}
